version: '3.8'

services:
  postgresmainservice:
    image: postgres:16-alpine
    hostname: postgresmainservice
    container_name: my-postgres
    restart: always
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  postgresauthservice:
    image: postgres:16-alpine
    hostname: postgresauthservice
    container_name: my-postgres-auth
    restart: always
    environment:
      - POSTGRES_DB=Time-tracker-auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  mainservice:
    build:
      context: ./MainService
    depends_on:
      - postgresmainservice
  auth:
    build:
      context: ./AuthorizationServer
    depends_on:
      - postgresauthservice
  api:
    build:
      context: ./ApiGateway
  eureka:
    build:
      context: ./EurekaServer
