version: '3.8'

services:
  postgresmainservice:
    image: postgres:16-alpine
    hostname: postgresmainservice
    container_name: my-postgres
    restart: always
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  mainservice:
    build:
      context: ./MainService
    depends_on:
      - postgresmainservice
  auth:
    build:
      context: ./AuthorizationServer
    depends_on:
      - postgresmainservice
  api:
    build:
      context: ./ApiGateway
    depends_on:
      - postgresmainservice
  eureka:
    build:
      context: ./EurekaServer
    depends_on:
      - postgresmainservice
